server:
  port: 8888

spring:
  application:
    name: seckillsystem
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckillsystem?useSSL=false&characterEncoding=utf8?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: root

# redis
  redis:
    database: 0
    port: 6379
    host: localhost

# mybatis
mybatis:
  mapper-locations: classpath:mapper/**/*.xml

# log
logging:
  level:
    root: info
    com.itjing.seckill.dao: debug


