server:
  port: 9999
# \u5173\u95EDthymeleaf\u7F13\u5B58
spring:
  thymeleaf:
    cache: false

# elasticsearch
elasticsearch:
  schema: http
  address: 127.0.0.1:9200
  connectTimeout: 5000
  socketTimeout: 5000
  connectionRequestTimeout: 5000
  maxConnectNum: 100
  maxConnectPerRoute: 100
