server:
  port: 5599

# spring 相关配置
spring:
  application:
    name: springboot-kafka
  # kafka 配置
  kafka:
    # 服务器地址及其 kafka 端口
    bootstrap-servers: 192.168.56.111:9092
    # 消费者配置
    consumer:
      # 消费者分组的id,可以在 kafka 的 config 目录下的 consumer.properties 中配置
      group-id: test-consumer-group
      # 是否自动提交消费者的偏移量
      enable-auto-commit: true
      # 自动提交的频率 3s
      auto-commit-interval: 3000